### ISSUE TITLE
CVAT起動(ubuntu)

### ISSUE THREAD

**Issue by kagami-tsukimura** [kagami-tsukimura/pytorch-deeplearning#78]
# CVATローカル起動手順(for Ubuntu)

CVAT（Computer Vision Annotation Tool）をUbuntu上で起動する手順を記載します。  
Dockerはすでにインストールされている前提で進めます。

## 手順

1. **リポジトリのクローン作成**

    ```bash
    git clone https://github.com/opencv/cvat
    ```

2. **バージョン指定してチェックアウト（デフォルトブランチでは起動時エラー）**

    ```bash
    cd cvat
    git checkout v2.9.2
    ```

3. **`docker-compose.yml`を以下のように修正**

    ```bash
    vim docker-compose.yml
    ```

   - `226`行目辺りの`command`をコメントアウトする。

    ```yaml
    traefik:
        image: traefik:v2.10
        container_name: traefik
        restart: always
        # command: <- ここをコメントアウト
        # labels:
        #   - traefik.enable=true
    ```

4. **`docker-compose.share.yml`の作成**

    ```
    vim docker-compose.share.yml
    ```

    - `docker-compose.share.yml`を以下の内容で作成する。

    ```yaml
    services:
      cvat_server:
        volumes:
          - cvat_share:/home/django/share:ro
      cvat_worker_import:
        volumes:
          - cvat_share:/home/django/share:ro
      cvat_worker_export:
        volumes:
          - cvat_share:/home/django/share:ro
      cvat_worker_annotation:
        volumes:
          - cvat_share:/home/django/share:ro

    volumes:
      cvat_share:
        driver_opts:
          type: none
          device: .
          o: bind
    ```

5. **docker composeを使用してコンテナを起動**

    ```bash
    CVAT_VERSION=v2.9.2 docker-compose -f docker-compose.yml -f docker-compose.share.yml up -d
    ```

6. **CVATサーバーにスーパーユーザーを作成**

    - ユーザー名、メールアドレス、パスワードを設定する。

    ```
    docker exec -it cvat_server bash -ic 'python3 ~/manage.py createsuperuser'
    ```

7. **ブラウザでCVATにアクセス**

    - ブラウザを開き、以下のURLにアクセスします。

    ```
    http://localhost:8080
    ```

以上で、CVATが正常に起動します。
